name: '🚀 publish'

on:
  push:
    branches:
      - master

jobs:
  release:
    name: 🚀 publish
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2.3.4
      # Setup .npmrc file to publish to npm
      - name: 🟢 node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
      - name: 🚀 publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      # Setup .npmrc file to publish to GitHub Packages
      - name: 🟢 node
        uses: actions/setup-node@v2.1.5
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: 🚀 publish
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}
